### ISSUE TITLE
Error in deployment

### ISSUE THREAD

**Issue by mrichman** [aws-solutions-library-samples/guidance-for-building-a-real-time-bidder-for-advertising-on-aws#11]
I got an error in CloudFormation when CodePipeline runs:

```
Embedded stack arn:aws:cloudformation:us-east-1:xxxxxxxxxxxx:stack/realtimebidding-DynamoDBStack-YMHEYMR3JFPC/fcfb2ec0-fa24-11ed-a4fc-0e094ddb4631 was not successfully created: The following resource(s) failed to create: [DeviceAudiencesTable].
```

There are no other logs that I can see.

**Comment by Aendapally** [comment]
Hi @mrichman, check the error logs for nested cloud formation stack which is creating the DynamoDB tables. Also check if you have increased quotas for DynamoDb rcu’s and wcu’s. If not reduce the rcu and wcu in the dynamodb.yaml file.

**Comment by mrichman** [comment]
Hi @Aendapally you're supposed to be on PTO! :) I just requested a quota increase to 150,000 RCUs. I should have read more closely. Thanks!
